language: ruby
rvm:
- 2.7

cache: bundler

before_script:
 - chmod +x ./script/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

sudo: false # route your build to the container-based infrastructure for a faster build
