title: iLtc
description: >- # this means to ignore newlines until "baseurl:"
  Technology and I
tagline: Technology and I
baseurl: /
url: https://blog.iltc.io
permalink: pretty

highlighter: none

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

plugins:
  - jekyll-feed
  - jekyll-gist

google_analytics: UA-108881767-2

show_excerpts: true
excerpt_separator: <!--more-->

disqus:
  shortname: iltc-blog